title: Quipt API Documentation
description: Documentation for the Quipt API
baseurl: ""
url: "https://getquipt.github.io"
remote_theme: just-the-docs/just-the-docs

# Tell Jekyll which files to include
include:
  - "*.md"
