openapi: 3.0.3
info:
  title: Quipt - OpenAPI 3.0
  description: >-
    View the [wiki](https://getquipt.github.io) for more details.
  version: 2.0.0
servers:
  - url: https://api.getquipt.com/v2
tags:
  - name: Vendor API - Inventory
    description: >- 
      Perform vendor workflows. 
      The inventory services below provide the ability to manage inventory listings within Quipt. 
      The provided services can be used manage everything from quantity synchronization to creating, publishing, and listing the inventory on partner sites. 
  - name: Vendor API - Orders
    description: >-
      The order services provide the ability to manage orders expected to be fulfilled by Quipt vendors. 
      The provided services may be used to download, acknowledge, ship, invoice, and cancel orders.
  - name: Vendor API - Shipments
    description: >-
      The shipment services provide a mechanism to manage shipments if your company is using ‘Ship via Quipt’.
      The primary purpose is to download the necessary packing and shipment documents. 
  - name: Vendor API - Requests
    description: >-
      The request services below provide the ability to manage requests expected to be completed by Quipt vendors. 
      The provided services can be used to download, acknowledge, and close requests. 
  - name: Channel API - Virtual Inventory
    description: >-
      The inventory services below provide the ability to manage virtual inventory listings within Quipt.
  - name: Channel API - Orders
    description: >-
      The order services provide the ability to manage orders expected to be fulfilled by Quipt vendors. 
      The provided services may be used to download, acknowledge, ship, invoice, and cancel orders. 
  - name: Channel API - Requests
    description: >-
      The request services below provide the ability to manage requests expected to be completed by Quipt vendors. 
      The provided services can be used to download, acknowledge, and close requests.
  - name: Catalog API
    description: Search product catalog.
  - name: Notification API
    description: >-
      Within Quipt users may subscribe to a defined set of events that occur throughout the application. 
      When an event is fired a notification is sent to the user. 
      The following API endpoints allow the user to access the notifications generated. 
      Currently the endpoints only allows the user to monitor for new messages and archive those that are no longer needed.

      Sample use cases.

      - Tracking movement through any work flow, ie Orders.

      - Monitor for changes, including price and quantity.
  - name: Carrier API
    description: >-
      Navigate the available carriers and related methods they support. **No authorization required for the endpoints listed below.**
  - name: Taxonomy API
    description: >-
      Navigate our taxonomy. **No authorization required for the endpoints listed below.**
      Categories are arranged in a tree structure, where:<br/>
      - Each category has a unique id.<br/>
      - A category can have multiple child categories.<br/>
      - A category must have IsLeaf: true to have a product assigned to it.
      - Any category may have Attributes associated, but refer to categories with IsLeaf: true to see those required for a category.
paths:
  /inventory/physical:
    post:
      tags:
        - Vendor API - Inventory
      summary: Add or update items.
      description: Add or update items.
      operationId: addUpdateInventoryItems
      security:
        - quipt_auth:
            - write:inventory
  /inventory/physical/report/{reportId}/{pageSize}/{pageNumber}:
    get:
      tags:
        - Vendor API - Inventory
      summary: Get job report details by ReportId.  
      description: This service allows a partner to retrieve the detailed report generated when the ‘Create/Update Inventory’ service is used. The result of ‘Create/Update Inventory’ returns the {id} used to retrieve the report from this service.
      operationId: getAddUpdateInventoryItemsReport
      security:
        - quipt_auth:
            - read:inventory  
  /inventory/physical/{pageSize}/{pageNumber}:
    get:
      tags:
        - Vendor API - Inventory
      summary: Get physical inventory items.
      description: >-
        Get a paged list of inventory items based on search parameters. 
        The service returns all inventory records created within Quipt. This includes both complete and incomplete inventory items.
      operationId: getPhysicalInventory
      security:
        - quipt_auth:
            - read:inventory
  /inventory/physical/id/{id}:
    get:
      tags:
        - Vendor API - Inventory
      summary: Get physical inventory item by id.
      description: Retrieve a specific physical inventory item by the Quipt identifier.
      operationId: getPhysicalInventoryById
      security:
        - quipt_auth:
            - read:inventory
  /inventory/GroupAndEnrich:
    post:
      tags:
        - Vendor API - Inventory
      summary: Group and enrich inventory items.
      description: >-
          The endpoint accepts an uploaded inventory file, aggregated by category, along with a selected template by name. The service parses the file, groups related inventory lines according to the template configuration, and enriches the data using Quipt’s catalog, partner pricing data, and the partne's existing inventory records.
          The result is a normalized dataset containing matched Quipt SKUs, grouped inventory units, partner pricing insights, and an estimated recovery value based on Quipt’s pricing model.  
      operationId: InventoryGroupAndEnrich
      security:
        - quipt_auth:
            - write:inventory
  /inventory/GroupAndEnrich/report/{reportId}:
    get:
      tags:
        - Vendor API - Inventory
      summary: Get group and enrich job report details by ReportId.  
      description: This service allows a partner to retrieve the detailed report generated when the ‘Group and Enrich Inventory’ service is used. The result of ‘Group and Enrich Inventory’ returns the {reportId} used to retrieve the report from this service.
      operationId: getGroupAndEnrichInventoryReport
      security:
        - quipt_auth:
            - read:inventory  
  /orders/fulfillment/{pageSize}/{pageNumber}:
    get:
      tags:
        - Vendor API - Orders
      summary: Get orders.
      description: Retrieve a paged list of orders placed by a channel.
      operationId: getFulfillmentOrders
      security:
        - quipt_auth:
            - read:orders
  /orders/fulfillment/id/{id}:
    get:
      tags:
        - Vendor API - Orders
      summary: Get order by id.
      description: Retrieve an order by the Quipt identifier.
      operationId: getFulfillmentOrdersById
      security:
        - quipt_auth:
            - read:orders
  /orders/fulfillment/po/{channelIdOrCode}/{poNumber}:
    get:
      tags:
        - Vendor API - Orders
      summary: Get order by purchase order number.
      description: Retrieve an order by the channel’s original order number.
      operationId: getFulfillmentOrdersByPO
      security:
        - quipt_auth:
            - read:orders
  /orders/fulfillment/channel/{channelIdOrCode}/{pageSize}/{pageNumber}:
    get:
      tags:
        - Vendor API - Orders
      summary: Get orders by channel.
      description: Retrieve a paged list of orders received by a specific channel.
      operationId: getFulfillmentOrdersByChannel
      security:
        - quipt_auth:
            - read:orders
  /orders/fulfillment/acknowledge:
    post:
      tags:
        - Vendor API - Orders
      summary: Acknowledge orders.
      description: >-
         Acknowledge an order. Use service provides the mechanisms to either accept and reject an order.
      operationId: ackFulfillmentOrders
      security:
        - quipt_auth:
            - write:orders
  /orders/fulfillment/ship:
    post:
      tags:
        - Vendor API - Orders
      summary: Ship orders.
      description: >-
         Apply shipment details to an order. Invoice details can be set as well.
      operationId: shipFulfillmentOrders
      security:
        - quipt_auth:
            - write:orders   
  /orders/fulfillment/invoice:
    post:
      tags:
        - Vendor API - Orders
      summary: Invoice orders.
      description: >-
          Invoice shipped orders. 
          Invoicing an order is required, but it is not required to be completed using this service. 
          If this flow cannot be supported, turn 'On' auto invoicing within company settings.
      operationId: invoiceFulfillmentOrders
      security:
        - quipt_auth:
            - write:orders
  /orders/fulfillment/archive:
    post:
      tags:
        - Vendor API - Orders
      summary: Archive orders.
      description: >-
        The primary purpose of archiving an order is to remove it from the lists that are obtained using ‘Get Orders’ and ‘Get Orders By Channel’.
        This mechanism is not required, and will be automatically applied after 30 days.
      operationId: archiveFulfillmentOrders
      security:
        - quipt_auth:
            - write:orders     
  /orders/fulfillment/report/{reportId}/{pageSize}/{pageNumber}:
    get:
      tags:
        - Vendor API - Orders
      summary: Get job report details by ReportId.  
      description: >-
        This service allows a partner to retrieve the detailed report generated when any of the action services are used. 
        The result of ‘Acknowledge Order’, ‘Ship Order’, ‘Invoice Order’, and ‘Archive Order’ returns the {id} used to retrieve the report from this service.
      operationId: getUpdateFulfillmentOrdersReport
      security:
        - quipt_auth:
            - read:orders  
  /orders/shipment/{pageSize}/{pageNumber}:
    get:
      tags:
        - Vendor API - Shipments
      summary: Get shipments.
      description: Retrieve a paged list of shipment records.
      operationId: getFulfillmentShipments
      security:
        - quipt_auth:
            - read:shipments
  /orders/shipment/id/{id}:
    get:
      tags:
        - Vendor API - Shipments
      summary: Get shipment by id.
      description: Get shipment by id.
      operationId: getFulfillmentShipmentsById
      security:
        - quipt_auth:
            - read:orders
  /orders/shipment/acknowledge:
    post:
      tags:
        - Vendor API - Shipments
      summary: Acknowledge shipments.
      description: >-
          This services allows a partner to acknowledge the receipt of a shipment.
      operationId: ackFulfillmentShipments
      security:
        - quipt_auth:
            - write:shipments
  /orders/shipment/report/{reportId}/{pageSize}/{pageNumber}:
    get:
      tags:
        - Vendor API - Shipments
      summary: Get job report details by ReportId.  
      description: >-
        This service allows a partner to retrieve the detailed report generated when any of the action services are used. 
        The result of ‘Acknowledge Shipment’ returns the {id} used to retrieve the report from this service.
      operationId: getUpdateFulfillmentShipmentsReport
      security:
        - quipt_auth:
            - read:shipments
  /requests/fulfillment/{pageSize}/{pageNumber}:
    get:
      tags:
        - Vendor API - Requests
      summary: Get requests.
      description: Retrieve a paged list of request records a partner has currently listed within Quipt.
      operationId: getFulfillmentRequests
      security:
        - quipt_auth:
            - read:requests
  /requests/fulfillment/{channelIdOrCode}/{pageSize}/{pageNumber}:
    get:
      tags:
        - Vendor API - Requests
      summary: Get requests by channel.
      description: Retrieve a paged list of request records for a specific channel.
      operationId: getFulfillmentRequestsByChannel
      security:
        - quipt_auth:
            - read:requests
  /requests/fulfillment/id/{id}:
    get:
      tags:
        - Vendor API - Requests
      summary: Get request by id.
      description: Retrieve a request record by its unique identifier.
      operationId: getFulfillmentRequestsById
      security:
        - quipt_auth:
            - read:requests
  /requests/fulfillment/acknowledge:
    post:
      tags:
        - Vendor API - Requests
      summary: Acknowledge requests.
      description: >-
         Acknowledge requests. It provides a mechanism to both accept and reject requests.
      operationId: ackFulfillmentRequests
      security:
        - quipt_auth:
            - write:requests
  /requests/fulfillment/create:
    post:
      tags:
        - Vendor API - Requests
      summary: Create request.
      description: >-
        Create a new request for a closed order.
      operationId: addFulfillmentRequests
      security:
        - quipt_auth:
            - write:requests
  /requests/fulfillment/returnupdate:
    post:
      tags:
        - Vendor API - Requests
      summary: Update return.
      description: >-
         Apply actions to return requests.
      operationId: updateFulfillmentRequestsReturn
      security:
        - quipt_auth:
            - write:requests
  /requests/fulfillment/missingaccessoryupdate:
    post:
      tags:
        - Vendor API - Requests
      summary: Missing Accessory Update.
      description: >-
          Apply actions to missing accessory requests.
      operationId: updateFulfillmentRequestsMissingAccessory
      security:
        - quipt_auth:
            - write:requests
  /requests/fulfillment/lostshipmentupdate:
    post:
      tags:
        - Vendor API - Requests
      summary: Lost Shipment Update.
      description: >-
          Apply actions to lost shipment requests.
      operationId: updateFulfillmentRequestsLostShipment
      security:
        - quipt_auth:
            - write:requests
  /requests/fulfillment/interceptupdate:
    post:
      tags:
        - Vendor API - Requests
      summary: Intercept Update
      description: >-
          Apply an action to an intercept request.
      operationId: updateFulfillmentRequestsIntercept
      security:
        - quipt_auth:
            - write:requests
  /requests/fulfillment/creditupdate:
    post:
      tags:
        - Vendor API - Requests
      summary: Credit Update.
      description: >-
          Apply an action to a credit request.
      operationId: updateFulfillmentRequestsCredit
      security:
        - quipt_auth:
            - write:requests
  /requests/fulfillment/cancel:
    post:
      tags:
        - Vendor API - Requests
      summary: Cancel Request.
      description: >-
          Request a cancellation of a fulfillment request.
      operationId: cancelFulfillmentRequests
      security:
        - quipt_auth:
            - write:requests
  /requests/fulfillment/archive:
    post:
      tags:
        - Vendor API - Requests
      summary: Archive Request.
      description: >-
        Archive requests. 
        The primary purpose of archiving a request is to remove it from the lists that are obtained using ‘Get Requests’ and ‘Get Requests By Channel’. 
        This mechanism is not required, and will be automatically applied after 30 days.
      operationId: archiveFulfillmentRequests
      security:
        - quipt_auth:
            - write:requests
  /requests/fulfillment/report/{reportId}/{pageSize}/{pageNumber}:
    get:
      tags:
        - Vendor API - Requests
      summary: Get job report details by ReportId.  
      description: >-
       This service allows a partner to retrieve the detailed report generated when any of the action services are used. 
       The result of ‘Acknowledge’, ‘Cancel’, ‘Create’, ‘Return Update’, ‘Lost Shipment Update’, ‘Intecept Update’, ‘Missing Accessory Update’, ‘Credit Update’ and ‘Archive’ returns the {id} used to retrieve the report from this service.
      operationId: getUpdateFulfillmentRequestsReport
      security:
        - quipt_auth:
            - read:shipments
  /inventory/virtual/acknowledge:
    post:
      tags:
        - Channel API - Virtual Inventory
      summary: Update virtual items.
      description: >-
          Let the vendor know you have listed or have an issue with the item they are selling.<br/>
          If listed forsale send the following properties within the request. 
            - ARP: { Optional, Current sale price. }<br/> 
            - CatalogStatus: 40<br/>
            - MapId: { Optional, Your internal identifier. }<br/>
            - MapURL: { Optional, The link to the item on your site. }<br/>
            
          If there is an issue send the following properties within the request.
             - CatalogStatus: 30<br/>
             - Messages: { The reason the item is not listed. }<br/>
      operationId: updateVirtualInventoryItems
      security:
        - quipt_auth:
            - write:feeds
  /inventory/virtual/report/{reportId}/{pageSize}/{pageNumber}:
    get:
      tags:
        - Channel API - Virtual Inventory
      summary: Get job report details by ReportId.  
      description: Get job report details by ReportId.
      operationId: getUpdateVirtualInventoryItemsReport
      security:
        - quipt_auth:
            - read:feeds 
  /inventory/virtual/{vendorId}/{pageSize}/{pageNumber}:
    get:
      tags:
        - Channel API - Virtual Inventory
      summary: Get virtual inventory items.
      description:  Retrieve a paged list of virtual inventory items currently listed by a specific vendor.
      operationId: getVirtualInventory
      security:
        - quipt_auth:
            - read:feeds
  /inventory/virtual/id/{id}:
    get:
      tags:
        - Channel API - Virtual Inventory
      summary: Get virtual inventory item by id.
      description: Get virtual inventory item by id.
      operationId: getVirtualInventoryById
      security:
        - quipt_auth:
            - read:feeds
  /orders/purchase/{pageSize}/{pageNumber}:
    get:
      tags:
        - Channel API - Orders
      summary: Get orders.
      description: Retrieve a paged list of orders placed by a channel.
      operationId: getPurchaseOrders
      security:
        - quipt_auth:
            - read:orders
  /orders/purchase/id/{id}:
    get:
      tags:
        - Channel API - Orders
      summary: Get order by id.
      description: Retrieve an order by its unique identifier.
      operationId: getPurchaseOrdersById
      security:
        - quipt_auth:
            - read:orders
  /orders/purchase/ordernumber/{poNumber}:
    get:
      tags:
        - Channel API - Orders
      summary: Get orders by purchase order number.
      description: Retrieve orders by the channel's original order number.
      operationId: getPurchaseOrdersByPO
      security:
        - quipt_auth:
            - read:orders
  /orders/purchase/create:
    post:
      tags:
        - Channel API - Orders
      summary: Create orders.
      description: >-
         Create purchase orders.
      operationId: addPurchaseOrders
      security:
        - quipt_auth:
            - write:requests
  /orders/purchase/acknowledge:
    post:
      tags:
        - Channel API - Orders
      summary: Acknowledge orders.
      description: >-
        Post purchase order acknowledgements to let vendor know you have an issue with the order.
      security:
        - quipt_auth:
            - write:requests
  /orders/purchase/cancel:
    post:
      tags:
        - Channel API - Orders
      summary: Cancel orders.
      description: >-
          Post purchase order cancel request.
      operationId: cancelPurchaseOrders
      security:
        - quipt_auth:
            - write:requests
  /orders/purchase/archive:
    post:
      tags:
        - Channel API - Orders
      summary: Archive orders.
      description: >-
        This service allows a partner to archive orders. 
        The primary purpose of archiving orders is to remove them from the lists that are obtained using ‘Get Orders’. 
        This mechanism is not required, and will be automatically applied after 30 days.
      operationId: archivePurchaseOrders
      security:
        - quipt_auth:
            - write:requests
  /orders/purchase/report/{reportId}/{pageSize}/{pageNumber}:
    get:
      tags:
        - Channel API - Orders
      summary: Get job report details by ReportId.  
      description: >-
        This service allows a partner to retrieve the detailed report generated when any of the action services are used. 
        The result of ‘Acknowledge Order’, ‘Ship Order’, ‘Invoice Order’, and ‘Archive Order’ returns the {id} used to retrieve the report from this service.
      operationId: getUpdatePurchaseOrdersReport
      security:
        - quipt_auth:
            - read:shipments
  /requests/purchase/{pageSize}/{pageNumber}:
    get:
      tags:
        - Channel API - Requests
      summary: Get requests.
      description: Retrieve a paged list of request records a partner has currently listed within Quipt..
      operationId: getPurchaseRequests
      security:
        - quipt_auth:
            - read:requests
  /requests/purchase/ordernumber/{poNumber}:
    get:
      tags:
        - Channel API - Requests
      summary: Get requests by purchase order number.
      description: Retrieve a list of request records by purchase order number.
      operationId: getPurchaseRequestsByPO
      security:
        - quipt_auth:
            - read:requests
  /requests/purchase/referencenumber/{refNumber}:
    get:
      tags:
        - Channel API - Requests
      summary: Get request by reference number.
      description: Retrieve a request record by reference number.
      operationId: getPurchaseRequestByRefNumber
      security:
        - quipt_auth:
            - read:requests
  /requests/purchase/id/{id}:
    get:
      tags:
        - Channel API - Requests
      summary: Get request by id.
      description: Retrieve a request record by id.
      operationId: getPurchaseRequestById
      security:
        - quipt_auth:
            - read:requests
  /requests/purchase/acknowledge:
    post:
      tags:
        - Channel API - Requests
      summary: Acknowledge requests.
      description: >-
          Let the vendor know you have an issue with the request.
      operationId: ackPurchaseRequests
      security:
        - quipt_auth:
            - write:requests
  /requests/purchase/create:
    post:
      tags:
        - Channel API - Requests
      summary: Create requests.
      description: >-
          Create a new request for a closed order.
      operationId: addPurchaseRequests
      security:
        - quipt_auth:
            - write:requests
  /requests/purchase/cancel:
    post:
      tags:
        - Channel API - Requests
      summary: Cancel purchase requests.
      description: >-
         Request a cancellation of a purchase request.
      operationId: cancelPurchaseRequests
      security:
        - quipt_auth:
            - write:requests
  /requests/purchase/archive:
    post:
      tags:
        - Channel API - Requests
      summary: Archive purchase requests.
      description: >-
          Archive requests. 
          The primary purpose of archiving an request is to remove it from the lists that are obtained using ‘Get Requests’. 
          This mechanism is not required, and will be automatically applied after 30 days.
      operationId: archivePurchaseRequests
      security:
        - quipt_auth:
            - write:requests
  /requests/purchase/report/{reportId}/{pageSize}/{pageNumber}:
    get:
      tags:
        - Channel API - Requests
      summary: Get job report details by ReportId.  
      description: >-
       Retrieve the detailed report generated when any of the action services are used. 
       The result of ‘Acknowledge’, ‘Cancel’, ‘Create’, ‘Return Update’, ‘Lost Shipment Update’, ‘Intercept Update’, ‘Missing Accessory Update’, ‘Credit Update’ and ‘Archive’ returns the {id} used to retrieve the report from this service.
      operationId: getUpdatePurchaseRequestsReport
      security:
        - quipt_auth:
            - read:requests
  /notifications/{pageSize}/{pageNumber}:
    get:
      tags:
        - Notification API
      summary: Get notifications. 
      description: >-
        This endpoint allows the user to monitor messages sent to their account. 
        Each of the specified types can be used to determine what additional API call can be utilized to get more details for a specific notification.
      operationId: getNotifications
      security:
        - quipt_auth:
            - read:notifications
  /notifications/update:
    post:
      tags:
        - Notification API
      summary: Update notifications.
      description: >-
         This endpoint allows a user to update a group of notifications.
      operationId: updateNotifications
      security:
        - quipt_auth:
            - write:notifications
  /notifications/archive:
    post:
      tags:
        - Notification API
      summary: Archive notifications.
      description: >-
         This endpoint allows a user to archive a group of notifications.
      operationId: archiveNotifications
      security:
        - quipt_auth:
            - write:notifications
  /notifications/report/{reportId}/{pageSize}/{pageNumber}:
    get:
      tags:
        - Notification API
      summary: Get job report details by ReportId.  
      description: This endpoint allows a user to retrieve the processing report for any batch notification transaction posted via API, ie Archive.
      operationId: getUpdateNotificationsReport
      security:
        - quipt_auth:
            - read:notifications
  /catalog/{pageSize}/{pageNumber}:
    get:
      tags:
        - Catalog API
      summary: Search product catalog.
      description: This endpoint allows the user to search our item catalog.
      operationId: getCatalogItems
      security:
        - quipt_auth:
            - read:inventory
  /carriers:
    get:
      tags:
        - Carrier API
      summary: Get supported carriers.
      description: This endpoint allows the user to get our carrier list.
      operationId: getCarriers
  /carriers/methods:
    get:
      tags:
        - Carrier API
      summary: Get supported carrier methods.
      description: This endpoint allows the user to retrieve supported carrier methods.
      operationId: getCarrierMethods
  /carriers/{carrierCodeOrId}/methods:
    get:
      tags:
        - Carrier API
      summary: Get supported carrier methods by carrier.
      description: This endpoint allows the user to retrieve the methods that belong to a specific carrier.
      operationId: getCarrierMethodsByCarrierCodeOrId
  /categories:
    get:
      tags:
        - Taxonomy API
      summary: Get root categories.
      description: >-
        Get top level categories defined within Quipt.
      operationId: getRootCategories
  /categories/{categoryId}:
    get:
      tags:
        - Taxonomy API
      summary:  Get children categories.
      description: >-
        Get children categories. Used to traverse the category tree. If the intention is to list against the selected category ensure IsLeaf is true.
      operationId: getCategoriesByParentId
  # /categories/search:        
  #   get:
  #     tags:
  #       - Taxonomy API
  #     summary: Get the categories that best match the provided keywords.  
  #     description: >-
  #       Get the categories that best match the provided keywords. One thing to keep in mind is we will perform 2 searches.
  #         1. Catalog search to identify relevant categories.
  #         2. Category tree search to identify categories that match provided keywords.
  #       Also, keep in mind returned categories may not have IsLeaf as true, so you will need to use getCategoriesbyParentId to identify a leaf category.
  #     operationId: getCategoriesByKeywords
  #     parameters:
  #       - name: keywords
  #         in: query
  #         description: >- 
  #           The tags/phrase to lookup.
  #         required: true
  #         schema:
  #           type: string
  #     responses:
  #       '200':
  #         description: Successful operation.
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/CategoryReply'
  #       '400':
  #         description: Invalid request.            
  /categories/{categoryId}/attributes:
    get:
      tags:
        - Taxonomy API
      summary: Get the attributes associated to the category. 
      description: >-
        Get the attributes associated to the category. If the intention is to list against the selected category ensure IsLeaf is true.
      operationId: getAttributesByCategoryId
components:
### schemas end ###   
  securitySchemes:
    quipt_auth:
      type: http
      scheme: basic
      description: >-
        ## Basic Authentication
        Enter username and password. 
        *Note:* Basic Authentication may only be used for *'Try It Out'* requests. Production integrations must use OAuth 1.0a authorization.
